add multi-line (>250 chars) support for long boosts into IRC messages
valcanobacon/BoostBots pull request #13
Opened 2022-04-06 02:08 UTC by dowodenum

Pretty simple, chunks() separates a long string into a list of strings, each element having a length no longer than 250. Then iterate through that list and send each chunk as an IRC message.

2022-04-09 22:57 UTC, valcanobacon requested changes
Thanks for this. Could you add some type annotations. A unit test for chunk would be great. Have you manually tested this?

2022-04-09 22:57 UTC, valcanobacon commented on src/irc/__init__.py
> +def chunks(l, n):
Can you add typing to this, I think the following should work. You need to `from typing import List` too.

```suggestion
def chunks(message: str, n: int) -> List[str]:
```

2022-04-09 22:57 UTC, valcanobacon commented on src/irc/__init__.py
> +    return (l[i : i + n] for i in range(0, len(l), n))
This is longer but might be easier to read

```suggestion
    for i in range(0, len(message), n):
        yield message[i: i + n]
```

2022-04-11 02:56 UTC, dowodenum commented
![image](https://user-images.githubusercontent.com/57815700/162656492-17f48fd5-15d9-4e40-ad08-aeb11941a892.png)

2022-04-12 03:28 UTC, valcanobacon approved these changes
This is great thanks!

2022-04-12 03:28 UTC, merged